//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.2.42
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace MyModels
{
	/// <summary>Grid Item Footer Atropos</summary>
	[PublishedContentModel("Footer")]
	public partial class Footer : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Footer";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Footer(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Footer, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		/// <summary>Address</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		/// <summary>Background Color</summary>
		[ImplementPropertyType("backgroundColor")]
		public object BackgroundColor
		{
			get { return this.GetPropertyValue("backgroundColor"); }
		}

		/// <summary>Background Color Top Bar</summary>
		[ImplementPropertyType("backgroundColorTopBar")]
		public object BackgroundColorTopBar
		{
			get { return this.GetPropertyValue("backgroundColorTopBar"); }
		}

		/// <summary>email</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		/// <summary>Facebook</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		/// <summary>Linkedin</summary>
		[ImplementPropertyType("linkedin")]
		public string Linkedin
		{
			get { return this.GetPropertyValue<string>("linkedin"); }
		}

		/// <summary>Logo</summary>
		[ImplementPropertyType("logo")]
		public object Logo
		{
			get { return this.GetPropertyValue("logo"); }
		}

		/// <summary>Master Color</summary>
		[ImplementPropertyType("masterColor")]
		public object MasterColor
		{
			get { return this.GetPropertyValue("masterColor"); }
		}

		/// <summary>Telephone Number</summary>
		[ImplementPropertyType("telephoneNumber")]
		public string TelephoneNumber
		{
			get { return this.GetPropertyValue<string>("telephoneNumber"); }
		}

		/// <summary>Text Color</summary>
		[ImplementPropertyType("textColor")]
		public object TextColor
		{
			get { return this.GetPropertyValue("textColor"); }
		}

		/// <summary>Twitter</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}
}
