//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.2.42
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace MyModels
{
	/// <summary>Layout</summary>
	[PublishedContentModel("Layout")]
	public partial class Layout : PublishedContentModel, IGoogleFont, IUmbracofields
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Layout";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Layout(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Layout, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		/// <summary>CSS</summary>
		[ImplementPropertyType("css")]
		public Archetype.Models.ArchetypeModel Css
		{
			get { return this.GetPropertyValue<Archetype.Models.ArchetypeModel>("css"); }
		}

		/// <summary>Footer Content</summary>
		[ImplementPropertyType("footerContent")]
		public Newtonsoft.Json.Linq.JToken FooterContent
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("footerContent"); }
		}

		/// <summary>Google Fonts</summary>
		[ImplementPropertyType("googleFont")]
		public Newtonsoft.Json.Linq.JToken GoogleFont
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("googleFont"); }
		}

		/// <summary>Header Content</summary>
		[ImplementPropertyType("headerContent")]
		public Newtonsoft.Json.Linq.JToken HeaderContent
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("headerContent"); }
		}

		/// <summary>Main Colors</summary>
		[ImplementPropertyType("mainColors")]
		public object MainColors
		{
			get { return this.GetPropertyValue("mainColors"); }
		}

		/// <summary>Seo</summary>
		[ImplementPropertyType("seoFields")]
		public Newtonsoft.Json.Linq.JToken SeoFields
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("seoFields"); }
		}

		/// <summary>umbracoInternalRedirectId</summary>
		[ImplementPropertyType("umbracointernalredirectid")]
		public object Umbracointernalredirectid
		{
			get { return this.GetPropertyValue("umbracointernalredirectid"); }
		}

		/// <summary>umbracoNaviHide</summary>
		[ImplementPropertyType("umbraconavihide")]
		public bool Umbraconavihide
		{
			get { return this.GetPropertyValue<bool>("umbraconavihide"); }
		}

		/// <summary>umbracoUrlName</summary>
		[ImplementPropertyType("umbracourlname")]
		public string Umbracourlname
		{
			get { return this.GetPropertyValue<string>("umbracourlname"); }
		}
	}
}
