//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.2.42
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace MyModels
{
	/// <summary>MyGift</summary>
	[PublishedContentModel("MyGift")]
	public partial class MyGift : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "MyGift";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public MyGift(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MyGift, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		/// <summary>Access Token</summary>
		[ImplementPropertyType("accessToken")]
		public string AccessToken
		{
			get { return this.GetPropertyValue<string>("accessToken"); }
		}

		/// <summary>City</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		/// <summary>Country</summary>
		[ImplementPropertyType("country")]
		public string Country
		{
			get { return this.GetPropertyValue<string>("country"); }
		}

		/// <summary>Date of Birth</summary>
		[ImplementPropertyType("dateOfBirth")]
		public DateTime DateOfBirth
		{
			get { return this.GetPropertyValue<DateTime>("dateOfBirth"); }
		}

		/// <summary>Facebook Image Url</summary>
		[ImplementPropertyType("facebookImageUrl")]
		public string FacebookImageUrl
		{
			get { return this.GetPropertyValue<string>("facebookImageUrl"); }
		}

		/// <summary>facebookUserId</summary>
		[ImplementPropertyType("facebookuserid")]
		public string Facebookuserid
		{
			get { return this.GetPropertyValue<string>("facebookuserid"); }
		}

		/// <summary>First Name</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		/// <summary>Gender</summary>
		[ImplementPropertyType("gender")]
		public object Gender
		{
			get { return this.GetPropertyValue("gender"); }
		}

		/// <summary>Last Name</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		/// <summary>Lists</summary>
		[ImplementPropertyType("lists")]
		public object Lists
		{
			get { return this.GetPropertyValue("lists"); }
		}

		/// <summary>Local</summary>
		[ImplementPropertyType("local")]
		public string Local
		{
			get { return this.GetPropertyValue<string>("local"); }
		}

		/// <summary>Name</summary>
		[ImplementPropertyType("name")]
		public string Name
		{
			get { return this.GetPropertyValue<string>("name"); }
		}

		/// <summary>Oauth Id</summary>
		[ImplementPropertyType("oauthId")]
		public string OauthId
		{
			get { return this.GetPropertyValue<string>("oauthId"); }
		}

		/// <summary>Picture</summary>
		[ImplementPropertyType("picture")]
		public string Picture
		{
			get { return this.GetPropertyValue<string>("picture"); }
		}

		/// <summary>Profile Picture</summary>
		[ImplementPropertyType("profilePicture")]
		public string ProfilePicture
		{
			get { return this.GetPropertyValue<string>("profilePicture"); }
		}

		/// <summary>Provider</summary>
		[ImplementPropertyType("provider")]
		public string Provider
		{
			get { return this.GetPropertyValue<string>("provider"); }
		}

		/// <summary>Region</summary>
		[ImplementPropertyType("region")]
		public string Region
		{
			get { return this.GetPropertyValue<string>("region"); }
		}

		/// <summary>Surname</summary>
		[ImplementPropertyType("surname")]
		public string Surname
		{
			get { return this.GetPropertyValue<string>("surname"); }
		}

		/// <summary>Is Approved</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		/// <summary>Comments</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public object UmbracoMemberComments
		{
			get { return this.GetPropertyValue("umbracoMemberComments"); }
		}

		/// <summary>Failed Password Attempts</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public object UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue("umbracoMemberFailedPasswordAttempts"); }
		}

		/// <summary>Last Lockout Date</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public object UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue("umbracoMemberLastLockoutDate"); }
		}

		/// <summary>Last Login Date</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public object UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue("umbracoMemberLastLogin"); }
		}

		/// <summary>Last Password Change Date</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public object UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue("umbracoMemberLastPasswordChangeDate"); }
		}

		/// <summary>Is Locked Out</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		/// <summary>Password Answer</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public object UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue("umbracoMemberPasswordRetrievalAnswer"); }
		}

		/// <summary>Password Question</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public object UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}
}
