//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.2.42
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace MyModels
{
	/// <summary>Page</summary>
	[PublishedContentModel("Page")]
	public partial class Page : PublishedContentModel, IUmbracofields
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Page";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Page(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Page, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		/// <summary>Background Content</summary>
		[ImplementPropertyType("backgroundContent")]
		public Newtonsoft.Json.Linq.JToken BackgroundContent
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("backgroundContent"); }
		}

		/// <summary>Content</summary>
		[ImplementPropertyType("content")]
		public Newtonsoft.Json.Linq.JToken Content
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
		}

		/// <summary>Seo</summary>
		[ImplementPropertyType("seoFields")]
		public Newtonsoft.Json.Linq.JToken SeoFields
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("seoFields"); }
		}

		/// <summary>umbracoInternalRedirectId</summary>
		[ImplementPropertyType("umbracointernalredirectid")]
		public object Umbracointernalredirectid
		{
			get { return this.GetPropertyValue("umbracointernalredirectid"); }
		}

		/// <summary>umbracoNaviHide</summary>
		[ImplementPropertyType("umbraconavihide")]
		public bool Umbraconavihide
		{
			get { return this.GetPropertyValue<bool>("umbraconavihide"); }
		}

		/// <summary>umbracoUrlName</summary>
		[ImplementPropertyType("umbracourlname")]
		public string Umbracourlname
		{
			get { return this.GetPropertyValue<string>("umbracourlname"); }
		}
	}
}
