//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Zbu.ModelsBuilder v2.1.2.42
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Zbu.ModelsBuilder;
using Zbu.ModelsBuilder.Umbraco;

namespace MyModels
{
	// Mixin content Type 1053 with alias "Umbracofields"
	/// <summary>_UmbracoFields</summary>
	public partial interface IUmbracofields : IPublishedContent
	{
		/// <summary>umbracoInternalRedirectId</summary>
		object Umbracointernalredirectid { get; }

		/// <summary>umbracoNaviHide</summary>
		bool Umbraconavihide { get; }

		/// <summary>umbracoUrlName</summary>
		string Umbracourlname { get; }
	}

	/// <summary>_UmbracoFields</summary>
	[PublishedContentModel("Umbracofields")]
	public partial class Umbracofields : PublishedContentModel, IUmbracofields
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Umbracofields";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Umbracofields(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Umbracofields, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		/// <summary>umbracoInternalRedirectId</summary>
		[ImplementPropertyType("umbracointernalredirectid")]
		public object Umbracointernalredirectid
		{
			get { return this.GetPropertyValue("umbracointernalredirectid"); }
		}

		/// <summary>umbracoNaviHide</summary>
		[ImplementPropertyType("umbraconavihide")]
		public bool Umbraconavihide
		{
			get { return this.GetPropertyValue<bool>("umbraconavihide"); }
		}

		/// <summary>umbracoUrlName</summary>
		[ImplementPropertyType("umbracourlname")]
		public string Umbracourlname
		{
			get { return this.GetPropertyValue<string>("umbracourlname"); }
		}
	}
}
